# Generated by Django 3.0.6 on 2020-06-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='completed',
        ),
        migrations.AddField(
            model_name='list',
            name='desc',
            field=models.CharField(default='Blank item', max_length=200),
        ),
        migrations.AlterField(
            model_name='list',
            name='item',
            field=models.CharField(default='Blank item', max_length=100),
        ),
    ]
